name: Upload Website to Alibaba Cloud OSS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fangbinwei/aliyun-oss-website-action@v1
        with:
          accessKeyId: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          accessKeySecret: ${{ secrets.ALIYUN_SECRET_ACCESS_KEY }}
          bucket: ${{ secrets.ALIYUN_OSS_BUCKET }}
          endpoint: oss-cn-beijing.aliyuncs.com
          folder: /
          exclude: |
            .git/
            .github/
            .idea/
            CNAME
